# This is a basic workflow to help you get started with Actions

name: Push Chart

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.2.0
        with:
          name: tootest-helm
          repository: appany
          tag: 0.1.0
          path: /
          registry: xom-ecomm-acr02-chart.cn-shanghai.cr.aliyuncs.com/tootest/tootest
          registry_username: cr_temp_user
          registry_password: eyJpbnN0YW5jZUlkIjoiY3JpLTNmeW5pYmVpZ2p4cGk1bzYiLCJ0aW1lIjoiMTYyOTIyODA5NzAwMCIsInR5cGUiOiJzdWIiLCJ1c2VySWQiOiIyNjAxMzg5MjA0NTQ2OTI5MDQifQ:ffdb0a2d240a1bdcc3feb015c82b5cd7185aec23

      # helm chart pull ghcr.io/appany/my-chart:0.1.0
      # helm chart export ghcr.io/appany/my-chart:0.1.0
